// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjFUAUZT3e6LbrfzvNXO-h4Calag8tbDs',
    appId: '1:844676731355:android:cca6faeefb0e48003717fe',
    messagingSenderId: '844676731355',
    projectId: 'testproject-8b58b',
    databaseURL: 'https://testproject-8b58b-default-rtdb.firebaseio.com',
    storageBucket: 'testproject-8b58b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgKzt1BoMGgb6kRjnPLRbmV2hbYEs8OEM',
    appId: '1:844676731355:ios:11d4cc47d16c6de33717fe',
    messagingSenderId: '844676731355',
    projectId: 'testproject-8b58b',
    databaseURL: 'https://testproject-8b58b-default-rtdb.firebaseio.com',
    storageBucket: 'testproject-8b58b.appspot.com',
    androidClientId:
        '844676731355-03l77j4hkjo578jn9m8jcj6jn5obqmn7.apps.googleusercontent.com',
    iosClientId:
        '844676731355-j7u1t6j6ilhonj4reobs168tdb7nv7ot.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
