// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:chat_app/features/chat/data/models/chat_model.dart';
import 'package:chat_app/features/message/data/models/message_model.dart';
import 'package:chat_app/features/profile/data/models/profile_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ChatModelAdapter());
    registerAdapter(MessageModelAdapter());
    registerAdapter(ProfileModelAdapter());
  }
}
